
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { MetricsData } from '../services/api';

interface PDFData {
    metrics: MetricsData | null;
    forecast: any[];
    workingCapital: any | null;
    inventory: any | null;
    loan: any | null;
    aiInsights: string[];
    industry: string;
}

export const generateInvestorReport = (data: PDFData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text('Financial Health Report', pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleDateString()} | Industry: ${data.industry}`, pageWidth / 2, 28, { align: 'center' });

    let y = 40;

    // 1. Executive Summary (Metrics)
    if (data.metrics) {
        doc.setFontSize(14);
        doc.setTextColor(44, 62, 80);
        doc.text('Executive Summary', 14, y);
        y += 10;

        const summaryData = [
            ['Revenue', `₹${data.metrics.total_revenue.toLocaleString()}`, 'Expenses', `₹${data.metrics.total_expenses.toLocaleString()}`],
            ['Net Profit', `₹${data.metrics.net_profit.toLocaleString()}`, 'Margin', `${data.metrics.profit_margin.toFixed(1)}%`],
            ['Cash Inflow', `₹${data.metrics.cash_inflow.toLocaleString()}`, 'Cash Outflow', `₹${data.metrics.cash_outflow.toLocaleString()}`]
        ];

        autoTable(doc, {
            startY: y,
            head: [['Metric', 'Value', 'Metric', 'Value']],
            body: summaryData,
            theme: 'striped',
            headStyles: { fillColor: [41, 128, 185] }
        });

        y = (doc as any).lastAutoTable.finalY + 15;
    }

    // 2. AI Insights
    if (data.aiInsights.length > 0) {
        doc.setFontSize(14);
        doc.text('Key AI Insights', 14, y);
        y += 8;

        doc.setFontSize(10);
        doc.setTextColor(60);
        data.aiInsights.forEach(insight => {
            const splitText = doc.splitTextToSize(`• ${insight}`, pageWidth - 30);
            doc.text(splitText, 14, y);
            y += splitText.length * 5;
        });
        y += 10;
    }

    // 3. Working Capital & Risk
    if (data.workingCapital) {
        doc.setFontSize(14);
        doc.setTextColor(44, 62, 80);
        doc.text('Working Capital & Risk Analysis', 14, y);
        y += 10;

        autoTable(doc, {
            startY: y,
            head: [['Gap', 'Receivables', 'Payables', 'Risk Level']],
            body: [[
                `₹${data.workingCapital.working_capital_gap?.toLocaleString() || 0}`,
                `₹${data.workingCapital.receivables?.toLocaleString() || 0}`,
                `₹${data.workingCapital.payables?.toLocaleString() || 0}`,
                data.workingCapital.risk_level?.toUpperCase() || 'N/A'
            ]],
            theme: 'grid',
            headStyles: { fillColor: [52, 73, 94] }
        });
        y = (doc as any).lastAutoTable.finalY + 15;
    }

    // 4. Forecast (3 Months)
    if (data.forecast && data.forecast.length > 0) {
        doc.setFontSize(14);
        doc.text('Financial Forecast (Next 3 Months)', 14, y);
        y += 10;

        const forecastRows = data.forecast.map(f => [
            f.month,
            `₹${Math.round(f.revenue).toLocaleString()}`,
            `₹${Math.round(f.expenses).toLocaleString()}`,
            `₹${Math.round(f.net_profit).toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: y,
            head: [['Month', 'Proj. Revenue', 'Proj. Expenses', 'Proj. Profit']],
            body: forecastRows,
            theme: 'plain',
            headStyles: { fillColor: [39, 174, 96] }
        });
        y = (doc as any).lastAutoTable.finalY + 15;
    }

    // 5. Debt & Inventory (If available)
    if (data.loan?.has_data || data.inventory?.has_data) {
        const debtInfo = data.loan?.has_data
            ? `Outstanding Debt: ₹${data.loan.total_outstanding.toLocaleString()} (EMI: ₹${data.loan.total_monthly_emi.toLocaleString()})`
            : 'No active loans recorded.';

        const stockInfo = data.inventory?.has_data
            ? `Inventory Value: ₹${data.inventory.total_value.toLocaleString()} (${data.inventory.total_items} items)`
            : 'No inventory data.';

        doc.setFontSize(14);
        doc.text('Assets & Liabilities Snapshot', 14, y);
        y += 8;
        doc.setFontSize(10);
        doc.text(`• ${debtInfo}`, 14, y);
        y += 6;
        doc.text(`• ${stockInfo}`, 14, y);
    }

    // Footer
    const pageCount = doc.internal.pages.length - 1;
    doc.setFontSize(8);
    doc.setTextColor(150);
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`Page ${i} of ${pageCount} - Generated by FinAnalyze`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' });
    }

    doc.save('FinAnalyze_Investor_Report.pdf');
};
